# Generated by Django 6.0.7 on 2026-07-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_event_recommendation_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Grad Banja Luka, NP RS, SC Borik...', max_length=100)),
                ('source_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='recommendation_score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'date', 'location'), name='unique_event'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='eventsource',
            constraint=models.UniqueConstraint(fields=('event', 'source_url'), name='unique_event_source'),
        ),
    ]
