# Generated by Django 6.0.7 on 2026-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventsource_remove_event_recommendation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_known',
            field=models.BooleanField(default=True),
        ),
    ]
