# Generated by Django 6.0.7 on 2026-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_savedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='npr: muzika, elektronska, festival (odvojeno zarezom)', max_length=255),
        ),
    ]
