# Generated by Django 6.0.7 on 2026-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_interest_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedevent',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
