# Generated by Django 6.0.7 on 2026-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_savedevent_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='source_url',
            field=models.URLField(max_length=500),
        ),
    ]
